mod api;
mod error;
mod runner;
pub(crate) mod support;

pub mod audit;
pub mod citations;
pub mod collect;
pub mod commands;
pub mod compile;
pub mod credibility;
pub mod daemon;
pub mod events;
pub mod exports;
pub mod frontmatter;
pub mod graph;
pub mod health;
pub mod indexer;
pub mod ingest;
pub mod links;
pub mod lint;
pub mod log;
pub mod markdown;
pub mod models;
pub mod output;
pub mod provenance;
pub mod registry;
pub mod research;
pub mod schema;
pub mod scope;
pub mod search;
pub mod session;
pub mod setup;
pub mod sources;
pub mod store;
pub mod synthesis;
pub mod transcribe;
pub mod vault;
pub mod video;
pub mod vision;

pub use api::{Command, CommandOutcome, CommandResult, ScopeIdentity, ScopeSelection};
pub use error::WikiError;
pub use runner::{resolve_research_scope, run};
